name       : python-hatch-nodejs-version
version    : 0.3.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/h/hatch_nodejs_version/hatch_nodejs_version-0.3.0.tar.gz : 7e08bd67fcd3dbfb97caf8f629a2173e4b117475ee51966f05a2169aaad06097
homepage   : https://github.com/agoose77/hatch-nodejs-version
license    : MIT
component  : programming.python
summary    : Hatch plugin to read pyproject.toml metadata from package.json
description: |
    This package provides two Hatch plugins. Version source plugin that reads/writes the package version from the version field of the Node.js package.json file and metadata hook plugin that reads PEP 621 metadata from the Node.js package.json file.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
    - python-pytest
rundeps    :
    - python-hatchling
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
